# 公共配置文件
spring:
  application:
    name: nxbi
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    async:
      request-timeout: 600000
  # session 配置
  session:
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nxbi
    username: root
    password: NXiang2002
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
wenxin:
  api-key: xxxxx
  secret-key: xxxxx

knife4j:
  enable: true
  setting:
    language: zh-CN
  basic:
    enable: true
    username: xxxxx
    password: xxxxx

# 限流器缓存配置
rate-limiter:
  # 初始容量
  initial-capacity: 5
  # 最大容量
  maximum-size: 100
  # 每秒请求数
  permits-per-second: 2.0

# 服务器推送事件缓存配置
sse:
  # 初始容量
  initial-capacity: 5
  # 最大容量
  maximum-size: 100
  # 超时时间
  time-out: 600000

# 线程池配置
thread-pool:
  # 核心线程数
  core-pool-size: 5
  # 最大线程数
  maximum-pool-size: 10
  # 非核心线程最大存活时间
  keep-alive-time: 30
  # 任务队列大小
  work-queue-size: 10
