server:
  port: 8081
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    username: xxxxxxxxxxxxxxx
    password: xxxxxxxxxxxxxxxxxx
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''